'use strict';


module.exports = function(Proxyinfo) {
  Proxyinfo.getProxyAssignedByList=function(ob,cb){
      Proxyinfo.find({
          where:{
            isCompleted:1,
            fOwnerid:ob.facultyId
          },
          include:{
            relation:"timetableRecordInfo",

            scope:{
              include:{
                relation:"timeTableInfo",
                scope:{
                  where:{
                    fAyearInfoId:ob.ayId
                  }
                }
                }
              }
          }
      }).then(rr=>{
        cb(null,rr)
      })
      .catch(error=>{
        cb(error,null)
      })
    }
    Proxyinfo.remoteMethod('getProxyAssignedByList',{
          accepts:[{
            arg:'detail',
            type:'Object'
          }],
          http:{
            path:'/getProxyAssignedByList/',
            verb:'post'
          },
          returns:{
           arg:'assignedByProxyList',
           type:'Object'
         }
    });

    Proxyinfo.getProxyAssignedToList=function(ob,cb){
        Proxyinfo.find({
            where:{
              isCompleted:1,
              fFacultyid:ob.facultyId
            },
            include:{
              relation:"timetableRecordInfo",
              scope:{
                  include:{
                    relation:"timeTableInfo",
                    scope:{
                      where:{
                        fAyearInfoId:ob.ayId
                      }
                    }
                  }
                }
            }
        }).then(rr=>{
          cb(null,rr)
        })
        .catch(error=>{
          cb(error,null)
        })
      }
      Proxyinfo.remoteMethod('getProxyAssignedToList',{
            accepts:[{
              arg:'detail',
              type:'Object'
            }],
            http:{
              path:'/getProxyAssignedToList/',
              verb:'post'
            },
            returns:{
             arg:'assignedToProxyList',
             type:'Object'
           }
      });
};
